title: NoFly
description: My Personal Stack Problems
author: NoFly
github: https://github.com/cofire
about: I am freelance developer. Currently doing more in backend, actually in Python and Django.
disqus_shortname: NoFly
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-skype
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"

share:
  twitter_username: cofire
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/cofire
    - text: XML Feed
      url: /feed.xml

url: "http:/nofly.cc"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - nofly-paginate
  - nofly-gist